### ISSUE TITLE
.NET Framework error

### ISSUE THREAD

**Issue by hookstein** [Xyene/BNSBoost#5]
Hey, just did a fresh Win7 install and I'm getting this after pressing 'launch' (tried1.2.2 and 1.30)
![clipboard01](https://cloud.githubusercontent.com/assets/28511698/25783565/5543f786-335e-11e7-86a6-6d72d6c4cac7.png)
[details.txt](https://github.com/Xyene/BNSBoost/files/981808/details.txt)

Worked fine before.

edit: OK I just noticed the other thread -_- I tried everything posted there, nothing works.

**Comment by Vedmik666** [comment]
Have same problem
While using BNSboost 1.3.0 on my old Windows 7 all was fine!!!
But now...
![1](https://user-images.githubusercontent.com/30435521/28570215-e0d7d66c-7145-11e7-9303-246c3805b113.PNG)
Net Framework 4.7
Windows 10 Pro x64
Have no idea how to fix this error((((((((((((

**Comment by Vedmik666** [comment]
Hey, I think I found a way
try to install Visual C++ 2015 Redistributable
it helps for me!!!!)))
