### ISSUE TITLE
Xigncode3 bns update

### ISSUE THREAD

**Issue by meguminrn** [Xyene/BNSBoost#6]
Since BNS is gonna  update their anti cheat system to Xigncode3, my question is,
is it still possible to use BNSboost after the update?

**Comment by zeffy** [comment]
I can't say with 100% certainty, but as long as the launcher isn't protected by XIGNCODE3, then I don't think anything will change, and you should still be able to use bnsboost. 

Also just a heads up, I've quit playing Blade&Soul, and I think Xyene is busy with other stuff (I could be wrong), so if there is a breaking change I don't know how soon bnsboost will be updated, if at all. So hopefully nothing breaks.

**Comment by Xyene** [comment]
@meguminrn @zeffy is spot on here, I just started an internship which consumes most of my time, so I don't have much to spend on Blade & Soul, and, by extension, BNSBoost.

That said, I think it's unlikely that BNSBoost will break anytime soon, as it's written in a highly update-proof way. It likely would have worked back in 2012 when the launcher was last updated, so I see no reason why it'd stop now &mdash; they never protected the launcher with GameGuard, so they probably won't protect it with XIGNCODE3 either.

**Comment by Kayo99** [comment]
@zeffy how about dps meter 6 mode is this still working ?

**Comment by zeffy** [comment]
@Kayo99 Like I said before, I couldn't say. I don't play BnS anymore, and frankly I'm not interested in letting them install this XIGNCODE3 crap on my computer just to test it out.

But unless they changed more than the game's anti-cheat system or if XC3 does its own integrity check on the games data files, I think you should still be able to turn on normal mode dps meter by editing xml.dat. I would recommend being cautious for now, though, until other people can confirm whether or not it works and aren't getting banned for it.

**Comment by Kayo99** [comment]
@zeffy how about this , do you think this is part of XC3 integrity check ? http://i.imgur.com/KpqFIks.png
PS: i only want DPS meter on 6 mode dungeons

**Comment by Xyene** [comment]
![](http://i.imgur.com/VaYZWcT.jpg)

Well, it definitely still works.

That copyright message is just simple metadata set on the assembly, nothing to be worried about there. I would still exercise caution in case XIGNCODE3 starts doing weird things, but functionally BNSBoost continues to work.

**Comment by Kayo99** [comment]
@Xyene i know its still working and i didn't mean the copyright message , what i mean is : do you think XmlReader_cl64.dll is part is XC3 integrity check ?

**Comment by zeffy** [comment]
@Kayo99 There's no way to know for sure without reverse engineering XC3, but if you are asking if a modified/hacked(?) XmlReader_cl64.dll would be detected by, then I would probably guess yes. Modifying game binaries is generally considered malicious by anti-cheat systems. But that is different from modifying xml.dat, which is just a packed and encrypted data file that contains many .xml files.

**Comment by Kayo99** [comment]
@zeffy so you mean its safe to edit xml.dat for dps meter ? i dont care about others edits

**Comment by zeffy** [comment]
@Kayo99 It is *possible*. But like I said already, I don't know if it is *safe*.

Also I think you might be slightly confused, if all you want to do is enable the dps meter, XmlReader_cl64.dll is completely unrelated to that.

**Comment by Kayo99** [comment]
@zeffy i thought Xmlreader_cl64.dll is there to read xml.dat if it has been modified or not since they add it with XC3...

**Comment by zeffy** [comment]
@Kayo99 Nope, XmlReader_cl64.dll is just a library they use to read/parse xml files and translate them into values the game can understand. It has been there long before XC3 was added, and has nothing to with it.

**Comment by Kayo99** [comment]
@zeffy Thank you and sorry for all my questions.

**Comment by zeffy** [comment]
No problem, happy to help!
